# Generated by Django 2.0.5 on 2018-07-18 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.CharField(choices=[('9AM-11AM', '9AM-11AM'), ('10AM-12PM', '10AM-12PM'), ('11AM-1PM', '11AM-1PM'), ('12PM-2PM', '12PM-2PM'), ('1PM-3PM', '1PM-3PM'), ('2PM-4PM', '2PM-4PM'), ('3PM-5PM', '3PM-5PM'), ('4PM-6PM', '4PM-6PM'), ('5PM-7PM', '5PM-7PM')], max_length=10)),
                ('day', models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('level_start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=0)),
                ('date_of_exam', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('voucher_id', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FeeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_fee', models.IntegerField()),
                ('level_fee', models.IntegerField()),
                ('exam_fee', models.IntegerField()),
                ('registration_fee', models.IntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('Level', 'Level'), ('Month', 'Month'), ('Exam', 'Exam'), ('Registration', 'Registration')], max_length=10)),
                ('fee_amount', models.IntegerField()),
                ('fee_receipt_no', models.IntegerField()),
                ('date_of_payment', models.DateField()),
                ('balance', models.IntegerField()),
                ('due', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('reserve_quantity', models.IntegerField(default=0)),
                ('reserve_quantity_max', models.IntegerField(default=5)),
                ('type', models.CharField(choices=[('Kit', 'Kit'), ('Book', 'Book'), ('Bookset', 'Bookset'), ('Question Paper', 'Question Paper')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Level-1', 'Level-1'), ('Level-2', 'Level-2'), ('Level-3', 'Level-3'), ('Level-4', 'Level-4'), ('Level-5', 'Level-5'), ('Level-6', 'Level-6'), ('Level-7', 'Level-7'), ('Level-8', 'Level-8'), ('Level-9', 'Level-9'), ('Level-10', 'Level-10'), ('Module-1', 'Module-1'), ('Module-2', 'Module-2'), ('Module-3', 'Module-3'), ('Module-4', 'Module-4')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='None', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RoyaltyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_royalty', models.IntegerField()),
                ('level_royalty', models.IntegerField()),
                ('exam_royalty', models.IntegerField()),
                ('registration_royalty', models.IntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_rate', models.IntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_type', models.CharField(choices=[('Level', 'Level'), ('Month', 'Month')], max_length=10)),
                ('salary_amount', models.IntegerField()),
                ('date_of_payment', models.DateField()),
                ('balance', models.IntegerField()),
                ('due', models.IntegerField()),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaryrecords', to='main.Batch')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaryrecords', to='main.Level')),
                ('months', models.ManyToManyField(related_name='salaryrecords', to='main.Month')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=5)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(max_length=13)),
                ('alt_phone', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('performance_rating', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=6, null=True)),
                ('dropped', models.BooleanField(default=False)),
                ('date_dropped', models.DateField(blank=True, null=True)),
                ('graduated', models.BooleanField(default=False)),
                ('date_graduated', models.DateField(blank=True, null=True)),
                ('t_shirt_size', models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('5XL', '5XL')], max_length=4, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='main.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('trained_max_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='main.Level')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_quantity', models.IntegerField()),
                ('operation', models.CharField(choices=[('Add', 'Add'), ('Remove', 'Remove')], max_length=6)),
                ('date', models.DateField()),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='main.Item')),
            ],
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaryrecords', to='main.Teacher'),
        ),
        migrations.AddField(
            model_name='item',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='main.Level'),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feerecords', to='main.Level'),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='months',
            field=models.ManyToManyField(related_name='feerecords', to='main.Month'),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feerecords', to='main.Student'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examresults', to='main.Level'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examresults', to='main.Student'),
        ),
        migrations.AddField(
            model_name='batch',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='main.Centre'),
        ),
        migrations.AddField(
            model_name='batch',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='main.Level'),
        ),
        migrations.AddField(
            model_name='batch',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='main.Teacher'),
        ),
    ]
