# Generated by Django 2.0.5 on 2018-07-08 05:20

from django.db import models, migrations

def load_all_from_fixtures(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "month")
    call_command("loaddata", "level")
    call_command("loaddata", "feerate")
    call_command("loaddata", "royaltyrate")
    call_command("loaddata", "salaryrate")
    call_command("loaddata", "centre")
    call_command("loaddata", "teacher")

def removeall(apps, schema_editor):
    #Removing items not removable from UI
    Month = apps.get_model("main", "Month")
    Month.objects.all().delete()
    Level = apps.get_model("main", "Level")
    Level.objects.all().delete()
    FeeRate = apps.get_model("main", "FeeRate")
    FeeRate.objects.all().delete()
    RoyaltyRate = apps.get_model("main", "RoyaltyRate")
    RoyaltyRate.objects.all().delete()
    SalaryRate = apps.get_model("main", "SalaryRate")
    SalaryRate.objects.all().delete()




class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_all_from_fixtures,removeall),
    ]
