# Generated by Django 2.0.5 on 2018-07-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fixture_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_graduated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='graduated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='t_shirt_size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('5XL', '5XL')], max_length=4, null=True),
        ),
    ]
